#!/usr/bin/env bash
# Automate Cloudflare Canyon tunnel: api.lab.minilab.work → local runtime.
#
# Prerequisites (pick one auth path):
#   A) Local-managed: run once `cloudflared tunnel login` (browser picks zone)
#   B) Remote API: CLOUDFLARE_API_TOKEN + CLOUDFLARE_ACCOUNT_ID (no cert.pem)
#
# Usage:
#   CANYON_HOSTNAME=api.lab.minilab.work CANYON_ORIGIN=http://127.0.0.1:3000 \
#     ./scripts/bootstrap-canyon.sh
#
# Env:
#   CANYON_TUNNEL_NAME   default: dream-machine-lab
#   CANYON_HOSTNAME      default: api.lab.minilab.work
#   CANYON_ORIGIN        default: http://127.0.0.1:3000
#   CLOUDFLARED_CONFIG   default: ~/.cloudflared/config.yml
set -euo pipefail

WS_ENV="$(cd "$(dirname "$0")/../.." && pwd)/.env"
if [[ -f "$WS_ENV" ]]; then set -a; # shellcheck disable=SC1090
  source "$WS_ENV"; set +a; fi

TUNNEL_NAME="${CANYON_TUNNEL_NAME:-dream-machine-lab}"
HOSTNAME="${CANYON_HOSTNAME:-api.lab.minilab.work}"
ORIGIN="${CANYON_ORIGIN:-http://127.0.0.1:3000}"
CONFIG="${CLOUDFLARED_CONFIG:-${HOME}/.cloudflared/config.yml}"
CF_DIR="$(dirname "$CONFIG")"

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "error: install cloudflared — brew install cloudflared" >&2
  exit 1
fi

mkdir -p "$CF_DIR"

tunnel_uuid() {
  cloudflared tunnel list -o json 2>/dev/null | python3 -c "
import json,sys
name=sys.argv[1]
try:
  data=json.load(sys.stdin)
except Exception:
  sys.exit(0)
for t in data or []:
  if t.get('name')==name:
    print(t.get('id',''))
    break
" "$TUNNEL_NAME" 2>/dev/null || true
}

create_tunnel_local() {
  if [[ -f "${CF_DIR}/cert.pem" ]]; then
    local id
    id="$(tunnel_uuid)"
    if [[ -z "$id" ]]; then
      echo "==> cloudflared tunnel create ${TUNNEL_NAME}"
      cloudflared tunnel create "$TUNNEL_NAME"
      id="$(tunnel_uuid)"
    fi
    echo "$id"
    return
  fi
  echo "error: run once: cloudflared tunnel login  (or set CLOUDFLARE_API_TOKEN + CLOUDFLARE_ACCOUNT_ID)" >&2
  exit 1
}

create_tunnel_api() {
  local resp id
  resp="$(curl -fsS "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/cfd_tunnel" \
    -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
    -H "Content-Type: application/json" \
    --data "{\"name\":\"${TUNNEL_NAME}\",\"config_src\":\"cloudflare\"}" 2>/dev/null || true)"
  id="$(printf '%s' "$resp" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('result',{}).get('id',''))" 2>/dev/null || true)"
  if [[ -z "$id" ]]; then
    id="$(tunnel_uuid)"
  fi
  if [[ -z "$id" ]]; then
    echo "error: could not create tunnel via API" >&2
    echo "$resp" >&2
    exit 1
  fi
  echo "$id"
}

if [[ -n "${CLOUDFLARE_API_TOKEN:-}" && -n "${CLOUDFLARE_ACCOUNT_ID:-}" ]]; then
  TUNNEL_ID="$(create_tunnel_api)"
  echo "==> tunnel id (API): ${TUNNEL_ID}"
  TOKEN_JSON="$(curl -fsS "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/cfd_tunnel/${TUNNEL_ID}/token" \
    -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}")"
  TUNNEL_TOKEN="$(printf '%s' "$TOKEN_JSON" | python3 -c "import json,sys; print(json.load(sys.stdin).get('result',''))")"
  if [[ -n "$TUNNEL_TOKEN" ]]; then
    echo "${TUNNEL_TOKEN}" > "${CF_DIR}/${TUNNEL_ID}.json"
    chmod 600 "${CF_DIR}/${TUNNEL_ID}.json"
  fi
else
  TUNNEL_ID="$(create_tunnel_local)"
  echo "==> tunnel id (local): ${TUNNEL_ID}"
fi

CREDS_FILE="${CF_DIR}/${TUNNEL_ID}.json"
if [[ ! -f "$CREDS_FILE" && -f "${CF_DIR}/${TUNNEL_ID}.json" ]]; then
  CREDS_FILE="${CF_DIR}/${TUNNEL_ID}.json"
fi

echo "==> DNS route ${HOSTNAME}"
cloudflared tunnel route dns -f "$TUNNEL_NAME" "$HOSTNAME" 2>/dev/null \
  || cloudflared tunnel route dns -f "$TUNNEL_ID" "$HOSTNAME"

cat >"$CONFIG" <<EOF
# Generated by Dream Machine bootstrap-canyon.sh
tunnel: ${TUNNEL_ID}
credentials-file: ${CREDS_FILE}

ingress:
  - hostname: ${HOSTNAME}
    service: ${ORIGIN}
  - service: http_status:404
EOF

echo "==> wrote ${CONFIG}"

if [[ "$(uname -s)" == "Darwin" ]]; then
  echo "==> install launch agent (macOS)"
  cloudflared service uninstall 2>/dev/null || true
  cloudflared --config "$CONFIG" service install
  echo "cloudflared service installed"
else
  echo "==> start tunnel (linux — consider: sudo cloudflared service install <token>)"
  echo "    cloudflared --config ${CONFIG} tunnel run ${TUNNEL_ID}"
fi

echo "done — test: curl -s -o /dev/null -w '%{http_code}' https://${HOSTNAME}/api/health"